# Paths
raw_data_path: './data/raw/'
meta_data_path: './data/raw/meta_data.csv'
processed_data_path: './data/processed/'
ckpt_path: './tb_logs/ms_pacman/vjepa_world_model/version_2/checkpoints/epoch=49-step=138850.ckpt'
# Pytorch
epochs: 50
# Game data
games: ['ms_pacman']

# Dataset parameters
batch_size: 32
num_workers: 0
shuffle: False

# Data pre-processing
original_size: [210, 160]
size_x: 84
size_y: 84
train_sub: ['R']
test_sub: ['K']
grey_scale: True
stack_length: &stack_length 4 # This is how you reuse parameters
sigma: 5
eye_density: True
use_fixations: True
maxdist: 25
sampling_rate: 1000

#vjepa
patchx: 21
patchy: 21
use_masking: True
tubelet_size: *stack_length # number of frames per tubelet

# Data writer parameters
data_writer:
  shard_write: False
  shard_maxcount: 6250
  data_write_freq: 3
